### ISSUE TITLE
Проверка хода пешки

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/chess#13]
Написать функцию, которая для заданных начальной и конечной клеток проверяет (возвращает True/False) возможность хода пешкой: наличие пешки на начальной клетке, отсутствие фигур на конечной, направление и расстояние между клетками. Для данного задания считать, что пешка может ходить только на оду клетку вперед.

**Comment by Likant** [comment]
добавил  функцию check_is_move_valid для проверки хода белой и ченрной пешки и изменид функцию check_pawn_move с учетом новой функции
